# Generated by Django 5.2.14 on 2026-05-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('score', models.TextField(default=0)),
                ('match_percentage', models.TextField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_skills', models.TextField(blank=True)),
            ],
        ),
    ]
